Now with if statement and exit code.

diff --git a/myscript b/myscript
--- a/myscript
+++ b/myscript
@@ -9,7 +9,12 @@ package=htop
 
 sudo apt install $package
 
-echo "The exit code for the package install is: $?"
+if [ $? -e 0 ] ; then
+  echo "The instalation of $package was succesful."
+  echo "$package is available here:"
+  which $package ; else
+  echo "$package failed to install."
+fi
 
 
 #############################
