Playing while while loop

diff --git a/myscript b/myscript
--- a/myscript
+++ b/myscript
@@ -9,20 +9,30 @@
 # 
 # https://www.gnu.org/licenses/gpl-3.0-standalone.html
 
+#############################
+
+myvar=1
+
+while [ $myvar -le 10 ]
+do
+  echo $myvar
+  myvar=$(( $myvar + 1 ))
+  sleep 0.5
+done
 
 
 #############################
 
-package=htop
+#package=htop
 
-sudo apt-get install $package >> package_install_results.log
+#sudo apt-get install $package >> package_install_results.log
 
-if [ $? -eq 0 ] ; then
-  echo "The installation of $package was succesful."
-  echo "$package is available here:"
-  which $package ; else
-  echo "$package failed to install." >> package_install_failure.log
-fi
+#if [ $? -eq 0 ] ; then
+#  echo "The installation of $package was succesful."
+#  echo "$package is available here:"
+#  which $package ; else
+#  echo "$package failed to install." >> package_install_failure.log
+#fi
 
 
 #############################
